// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT4XSpISFKYq2x4zHUm2ghOF0zfkm560E',
    appId: '1:535766701987:web:1c17f87453b8e6339a2c16',
    messagingSenderId: '535766701987',
    projectId: 'final-project-d9c7c',
    authDomain: 'final-project-d9c7c.firebaseapp.com',
    storageBucket: 'final-project-d9c7c.appspot.com',
    measurementId: 'G-0SWTEPMJ87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVPlp9KAZrL3z6d6mwV_--mi4jN0BYS8',
    appId: '1:535766701987:android:805f3a73fe4de48d9a2c16',
    messagingSenderId: '535766701987',
    projectId: 'final-project-d9c7c',
    storageBucket: 'final-project-d9c7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS3YBzAJTHTr2HH8hcLNT9xi1za2pEnX0',
    appId: '1:535766701987:ios:1a8c9ce56e5d9e8b9a2c16',
    messagingSenderId: '535766701987',
    projectId: 'final-project-d9c7c',
    storageBucket: 'final-project-d9c7c.appspot.com',
    iosClientId: '535766701987-64st6s79be2117uk7v8vjm8dnfruck0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS3YBzAJTHTr2HH8hcLNT9xi1za2pEnX0',
    appId: '1:535766701987:ios:1a8c9ce56e5d9e8b9a2c16',
    messagingSenderId: '535766701987',
    projectId: 'final-project-d9c7c',
    storageBucket: 'final-project-d9c7c.appspot.com',
    iosClientId: '535766701987-64st6s79be2117uk7v8vjm8dnfruck0d.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );
}
